name: Deploy portfolio

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build portfolio
        run: npm run build

      - name: Create deployment directory
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ssh.simply.com
          port: 22
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: mkdir -p lineamoltved.com

      - name: Upload portfolio
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ssh.simply.com
          port: 22
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: dist/.htaccess,dist/*
          target: lineamoltved.com
          strip_components: 1
